### ISSUE TITLE
Linstor-GUI Config file

### ISSUE THREAD

**Issue by cduchenoy** [RumenBlack84/linstor-gui-docker#1]
Hi,

Like you, I tried to understand where the configuration files were :)

In fact, they directly use the key-value basis of the Linstor controller

cf:

![linstor-gui-db](https://github.com/user-attachments/assets/fc078fb7-2fcc-46a4-b620-f7c0a26b2423)

We created a patch for the Dockerfile and the entrypoint because the volume is no longer necessary

We will send a PR asap

Thank you for your job

Cyril from Geco-iT

**Comment by RumenBlack84** [comment]
merged
